// <auto-generated />
using System;
using EvaluacionCore.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Workflow.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnrolApp.Domain.Entities.Common.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("CargoPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cargoPadreId")
                        .HasColumnOrder(4);

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("departamentoId")
                        .HasColumnOrder(1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(3);

                    b.Property<string>("Estado")
                        .HasColumnType("varchar")
                        .HasColumnName("estado")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(9);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar")
                        .HasColumnName("nombre")
                        .HasColumnOrder(2);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("varchar")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(6);

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("WF_Cargo", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.ClaseTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("CodigoClaseturno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoClaseTurno")
                        .HasColumnOrder(1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("A");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(4);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("AS_ClaseTurno", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Localidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(6);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(9)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(11);

                    b.Property<Guid>("IdCanton")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCanton");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idEmpresa")
                        .HasColumnOrder(1);

                    b.Property<double>("Latitud")
                        .HasMaxLength(8)
                        .HasColumnType("float")
                        .HasColumnName("latitud")
                        .HasColumnOrder(3);

                    b.Property<double>("Longitud")
                        .HasMaxLength(8)
                        .HasColumnType("float")
                        .HasColumnName("longitud")
                        .HasColumnOrder(4);

                    b.Property<double>("Radio")
                        .HasMaxLength(8)
                        .HasColumnType("float")
                        .HasColumnName("radio")
                        .HasColumnOrder(5);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(8);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("IdCanton");

                    b.ToTable("AS_Localidad", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.LocalidadColaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<bool?>("EsPrincipal")
                        .HasColumnType("bit")
                        .HasColumnName("esPrincipal")
                        .HasColumnOrder(8);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("estado")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(7);

                    b.Property<Guid>("IdColaborador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idColaborador")
                        .HasColumnOrder(2);

                    b.Property<Guid>("IdLocalidad")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLocalidad")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(4);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("AS_LocalidadColaborador", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.MarcacionColaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("EstadoMarcacionEntrada")
                        .HasColumnType("varchar")
                        .HasColumnName("estadoMarcacionEntrada")
                        .HasColumnOrder(5);

                    b.Property<bool>("EstadoProcesado")
                        .HasColumnType("bit")
                        .HasColumnName("estadoProcesado")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(10)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(12);

                    b.Property<Guid>("IdLocalidadColaborador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLocalidadColaborador")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("IdTurnoColaborador")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTurnoCliente")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("MarcacionEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("marcacionEntrada")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("MarcacionSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("marcacionSalida")
                        .HasColumnOrder(4);

                    b.Property<string>("SalidaEntrada")
                        .HasColumnType("varchar")
                        .HasColumnName("estadoMarcacionSalida")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("TotalAtraso")
                        .HasColumnType("datetime2")
                        .HasColumnName("totalAtraso")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(9);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("IdLocalidadColaborador");

                    b.HasIndex("IdTurnoColaborador");

                    b.ToTable("AS_MarcacionColaborador", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.SubclaseTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("CodigoSubclaseTurno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoSubclase")
                        .HasColumnOrder(1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("A");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(4);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("AS_SubclaseTurno", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.TipoTurno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("CodigoTurno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoTurno")
                        .HasColumnOrder(1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("A");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(5)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(4);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("AS_TipoTurno", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<int?>("CodigoEntrada")
                        .HasColumnType("int")
                        .HasColumnName("codigoEntrada")
                        .HasColumnOrder(22);

                    b.Property<string>("CodigoIntegracion")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoIntegracion")
                        .HasColumnOrder(8);

                    b.Property<int?>("CodigoSalida")
                        .HasColumnType("int")
                        .HasColumnName("codigoSalida")
                        .HasColumnOrder(23);

                    b.Property<string>("CodigoTurno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigoTurno")
                        .HasColumnOrder(7);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime")
                        .HasColumnName("entrada")
                        .HasColumnOrder(10);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(13)
                        .HasDefaultValueSql("A");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(15)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(17);

                    b.Property<Guid>("IdClaseTurno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idClaseTurno")
                        .HasColumnOrder(3);

                    b.Property<Guid>("IdModalidadJornada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idModalidadJornada")
                        .HasColumnOrder(6);

                    b.Property<Guid>("IdSubclaseTurno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idSubclaseTurno")
                        .HasColumnOrder(4);

                    b.Property<Guid>("IdTipoJornada")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTipoJornada")
                        .HasColumnOrder(5);

                    b.Property<Guid>("IdTipoTurno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTipoTurno")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("IdTurnoPadre")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTurnoPadre")
                        .HasColumnOrder(1);

                    b.Property<int?>("MargenEntradaGracia")
                        .HasColumnType("int")
                        .HasColumnName("margenEntradaGracia")
                        .HasColumnOrder(20);

                    b.Property<int?>("MargenEntradaPrevio")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("margenEntradaPrevio")
                        .HasColumnOrder(18);

                    b.Property<int?>("MargenSalidaGracia")
                        .HasColumnType("int")
                        .HasColumnName("margenSalidaGracia")
                        .HasColumnOrder(21);

                    b.Property<int?>("MargenSalidaPosterior")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("margenSalidaPosterior")
                        .HasColumnOrder(19);

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime")
                        .HasColumnName("salida")
                        .HasColumnOrder(11);

                    b.Property<string>("TotalHoras")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("totalHoras")
                        .HasColumnOrder(12);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(14);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(16);

                    b.HasKey("Id");

                    b.HasIndex("IdClaseTurno");

                    b.HasIndex("IdSubclaseTurno");

                    b.HasIndex("IdTipoTurno");

                    b.ToTable("AS_Turno", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.TurnoColaborador", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaAsginacion")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(8);

                    b.Property<Guid>("IdColaborador")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idColaborador")
                        .HasColumnOrder(2);

                    b.Property<Guid>("IdTurno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTurno")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(5);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdTurno");

                    b.ToTable("AS_TurnoColaborador", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.CalendarioLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<bool?>("EsRecuperable")
                        .HasColumnType("bit")
                        .HasColumnName("esRecuperable")
                        .HasColumnOrder(5);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("FechaConmemorativa")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaConmemorativa")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("FechaFestiva")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFestiva")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(10);

                    b.Property<Guid>("IdCanton")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCanton")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("IdCanton");

                    b.ToTable("AS_CalendarioLocal", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.CalendarioNacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<bool?>("EsRecuperable")
                        .HasColumnType("bit")
                        .HasColumnName("esRecuperable")
                        .HasColumnOrder(5);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("FechaConmemorativa")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaConmemorativa")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("FechaFestiva")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFestiva")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(10);

                    b.Property<Guid>("IdPais")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPais")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("AS_CalendarioNacional", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Canton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(3);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(8);

                    b.Property<Guid>("IdProvincia")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idProvincia")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(5);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.ToTable("AS_Canton", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(4);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("AS_Pais", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion")
                        .HasColumnOrder(3);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(6);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(8);

                    b.Property<Guid>("IdPais")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPais")
                        .HasColumnOrder(1);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(5);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("AS_Provincia", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Common.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("alias")
                        .HasColumnOrder(7);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellidos")
                        .HasColumnOrder(6);

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cargoId")
                        .HasColumnOrder(21);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("celular")
                        .HasColumnOrder(11);

                    b.Property<Guid?>("ClientePadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("clientePadreId")
                        .HasColumnOrder(22);

                    b.Property<string>("CodigoConvivencia")
                        .HasColumnType("varchar")
                        .HasColumnName("codigoConvivencia")
                        .HasColumnOrder(2);

                    b.Property<string>("CodigoIntegracion")
                        .HasColumnType("varchar")
                        .HasColumnName("codigoIntegracion")
                        .HasColumnOrder(1);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("correo")
                        .HasColumnOrder(14);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion")
                        .HasColumnOrder(10);

                    b.Property<string>("DispositivoId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dispositivoId")
                        .HasColumnOrder(20);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(19);

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaNacimiento")
                        .HasColumnOrder(15);

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasColumnOrder(17)
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("genero")
                        .HasColumnOrder(16);

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("identificacion")
                        .HasColumnOrder(4);

                    b.Property<string>("IndentificacionFamiliar")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("indentificacionFamiliar")
                        .HasColumnOrder(13);

                    b.Property<double>("Latitud")
                        .HasColumnType("float")
                        .HasColumnName("latitud")
                        .HasColumnOrder(8);

                    b.Property<double>("Longitud")
                        .HasColumnType("float")
                        .HasColumnName("longitud")
                        .HasColumnOrder(9);

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("varchar")
                        .HasColumnName("nombreUsuario")
                        .HasColumnOrder(23);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombres")
                        .HasColumnOrder(5);

                    b.Property<bool>("ServicioActivo")
                        .HasColumnType("bit")
                        .HasColumnName("servicioActivo")
                        .HasColumnOrder(18);

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tipoIdentificacion")
                        .HasColumnOrder(3);

                    b.Property<string>("TipoIdentificacionFamiliar")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipoIdentificacionFamiliar")
                        .HasColumnOrder(12);

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.ToTable("CL_Cliente", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.EstadoTarea", b =>
                {
                    b.Property<Guid>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idEstado");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioCreacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioModificacion");

                    b.HasKey("IdEstado");

                    b.ToTable("WF_EstadoTarea", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Justificacion.SolicitudJustificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("CodOrganizacion")
                        .HasColumnType("int")
                        .HasColumnName("codOrganizacion");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comentarios");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion");

                    b.Property<Guid>("IdEstadoSolicitud")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idEstadoSolicitud");

                    b.Property<int?>("IdMarcacion")
                        .HasColumnType("int")
                        .HasColumnName("idMarcacion");

                    b.Property<Guid>("IdTipoJustificacion")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTipoJustificacion");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("idTurno");

                    b.Property<string>("IdentBeneficiario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identBeneficiario");

                    b.Property<string>("IdentificacionEmpleado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identificacionEmpleado");

                    b.Property<DateTime>("MarcacionEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("marcacionEntrada");

                    b.Property<DateTime>("MarcacionSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("marcacionSalida");

                    b.Property<DateTime>("TurnoEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("turnoEntrada");

                    b.Property<DateTime>("TurnoSalida")
                        .HasColumnType("datetime2")
                        .HasColumnName("turnoSalida");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioCreacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioModificacion");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdTipoJustificacion");

                    b.ToTable("AS_SolicitudJustificacion", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Justificacion.TipoJustificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioCreacion");

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuarioModificacion");

                    b.HasKey("Id");

                    b.ToTable("WF_TipoJustificacion", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("empresaId")
                        .HasColumnOrder(1);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("OG_Area", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("areaId")
                        .HasColumnOrder(1);

                    b.Property<string>("Codigo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("OG_Departamento", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(2);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(7);

                    b.Property<Guid>("GrupoEmpresarialId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grupoEmpresarialId")
                        .HasColumnOrder(1);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary")
                        .HasColumnName("logo")
                        .HasColumnOrder(6);

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombreComercial")
                        .HasColumnOrder(4);

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("razonSocial")
                        .HasColumnOrder(5);

                    b.Property<string>("Ruc")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("ruc")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("GrupoEmpresarialId");

                    b.ToTable("OG_Empresa", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.GrupoEmpresarial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Codigo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("codigo")
                        .HasColumnOrder(1);

                    b.Property<string>("Estado")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("estado")
                        .HasColumnOrder(4);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary")
                        .HasColumnName("logo")
                        .HasColumnOrder(3);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("OG_GrupoEmpresarial", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioCab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiasRecordatorio")
                        .HasColumnType("int")
                        .HasColumnName("diasRecordatorio");

                    b.Property<string>("Estado")
                        .HasColumnType("varchar")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaEvaluacion");

                    b.Property<Guid>("IdJefe")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idJefe");

                    b.Property<string>("TipoRecordatorio")
                        .HasColumnType("varchar")
                        .HasColumnName("tipoRecordatorio");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("AS_NovedadRecordatorioCab", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioDet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasColumnType("varchar")
                        .HasColumnName("area");

                    b.Property<int>("CodBiometricoColaborador")
                        .HasColumnType("int")
                        .HasColumnName("codBiometricoColaborador");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaEvaluacion");

                    b.Property<DateTime>("FechaNoAsignada")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaNoAsignada");

                    b.Property<Guid>("IdNovedadRecordatorioCab")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNovedadRecordatorioCab");

                    b.Property<string>("IdentificacionColaborador")
                        .HasColumnType("varchar")
                        .HasColumnName("identificacionColaborador");

                    b.Property<string>("NombreColaborador")
                        .HasColumnType("varchar")
                        .HasColumnName("nombreColaborador");

                    b.Property<Guid?>("NovedadRecordatorioCabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubcentroCosto")
                        .HasColumnType("varchar")
                        .HasColumnName("subCentroCosto");

                    b.Property<string>("Udn")
                        .HasColumnType("varchar")
                        .HasColumnName("udn");

                    b.HasKey("Id");

                    b.HasIndex("NovedadRecordatorioCabId");

                    b.ToTable("AS_NovedadRecordatorioDet", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.Recordatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaLimite");

                    b.Property<DateTime>("FinRecordatorio")
                        .HasColumnType("datetime")
                        .HasColumnName("finRecordatorio");

                    b.Property<Guid>("IdPlantilla")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPlantillaSms");

                    b.Property<DateTime>("InicioRecordatorio")
                        .HasColumnType("datetime")
                        .HasColumnName("inicioRecordatorio");

                    b.Property<string>("PeriodoRecordatorio")
                        .HasColumnType("varchar")
                        .HasColumnName("periodoRecordatorio");

                    b.HasKey("Id");

                    b.ToTable("AS_Recordatorio", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.SolicitudPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("CantidadDias")
                        .HasColumnType("int")
                        .HasColumnName("cantidadDias ");

                    b.Property<DateTime?>("CantidadHoras")
                        .HasColumnType("datetime2")
                        .HasColumnName("cantidadHoras ");

                    b.Property<int?>("CodOrganizacion")
                        .HasColumnType("int")
                        .HasColumnName("codOrganizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion ");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaDesde ");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaHasta ");

                    b.Property<string>("HoraFin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("horaFin ");

                    b.Property<string>("HoraInicio")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("horaInicio ");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int")
                        .HasColumnName("idBeneficiario ");

                    b.Property<Guid>("IdEstadoSolicitud")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idEstadoSolicitud");

                    b.Property<int>("IdSolicitante")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitante ");

                    b.Property<Guid>("IdTipoPermiso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTipoPermiso");

                    b.Property<string>("IdentificacionEmpleado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identificacionEmpleado");

                    b.Property<int>("NumeroSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("numeroSolicitud ");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacion ");

                    b.Property<bool?>("PorHoras")
                        .HasColumnType("bit")
                        .HasColumnName("porHoras ");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdTipoPermiso");

                    b.ToTable("AS_SolicitudPermiso", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.TipoPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("estado");

                    b.HasKey("Id");

                    b.ToTable("WF_TipoPermiso", "dbo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Vacaciones.SolicitudVacacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CantidadDias")
                        .HasColumnType("int")
                        .HasColumnName("cantidadDias");

                    b.Property<int?>("CodOrganizacion")
                        .HasColumnType("int")
                        .HasColumnName("codOrganizacion");

                    b.Property<string>("CodigoEmpleadoReemplazo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigoEmpleadoReemplazo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaDesde");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaHasta");

                    b.Property<int>("IdBeneficiario")
                        .HasColumnType("int")
                        .HasColumnName("idBeneficiario");

                    b.Property<Guid>("IdEstadoSolicitud")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idEstadoSolicitud");

                    b.Property<int>("IdSolicitante")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitante");

                    b.Property<Guid>("IdTipoSolicitud")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTipoSolicitud");

                    b.Property<string>("IdentificacionEmpleado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("identificacionEmpleado");

                    b.Property<int>("NumeroSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("numeroSolicitud");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observacion");

                    b.Property<Guid?>("TipoPermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("TipoPermisoId");

                    b.ToTable("AS_SolicitudVacacion", "dbo");
                });

            modelBuilder.Entity("EnrolApp.Domain.Entities.Common.Cargo", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Organizacion.Departamento", "Departamento")
                        .WithMany("Cargos")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Localidad", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Calendario.Canton", "Canton")
                        .WithMany("Localidades")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.LocalidadColaborador", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Common.Cliente", "Colaborador")
                        .WithMany("LocalidadColaboradores")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.Localidad", "Localidad")
                        .WithMany("LocalidadColaboradores")
                        .HasForeignKey("IdLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.MarcacionColaborador", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.LocalidadColaborador", "LocalidadColaborador")
                        .WithMany("MarcacionColaboradores")
                        .HasForeignKey("IdLocalidadColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.TurnoColaborador", "TurnoColaborador")
                        .WithMany("MarcacionColaboradores")
                        .HasForeignKey("IdTurnoColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalidadColaborador");

                    b.Navigation("TurnoColaborador");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Turno", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.ClaseTurno", "ClaseTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("IdClaseTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.SubclaseTurno", "SubclaseTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("IdSubclaseTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.TipoTurno", "TipoTurno")
                        .WithMany("Turnos")
                        .HasForeignKey("IdTipoTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaseTurno");

                    b.Navigation("SubclaseTurno");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.TurnoColaborador", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Common.Cliente", "Colaborador")
                        .WithMany("TurnoColaboradores")
                        .HasForeignKey("IdColaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Asistencia.Turno", "Turno")
                        .WithMany("TurnoColaboradores")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.CalendarioLocal", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Calendario.Canton", "Canton")
                        .WithMany("CalendariosLocal")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.CalendarioNacional", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Calendario.Pais", "Pais")
                        .WithMany("CalendarioNacional")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Canton", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Calendario.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Provincia", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Calendario.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Common.Cliente", b =>
                {
                    b.HasOne("EnrolApp.Domain.Entities.Common.Cargo", "Cargo")
                        .WithMany("Clientes")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Justificacion.SolicitudJustificacion", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.EstadoTarea", "EstadoTarea")
                        .WithMany("SolicitudJustificacion")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Justificacion.TipoJustificacion", "TipoJustificacion")
                        .WithMany("SolicitudJustificacion")
                        .HasForeignKey("IdTipoJustificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoTarea");

                    b.Navigation("TipoJustificacion");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Area", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Organizacion.Empresa", "Empresa")
                        .WithMany("Areas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Departamento", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Organizacion.Area", "Area")
                        .WithMany("Departamentos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Empresa", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Organizacion.GrupoEmpresarial", "GrupoEmpresarial")
                        .WithMany("Empresas")
                        .HasForeignKey("GrupoEmpresarialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEmpresarial");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioCab", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Common.Cliente", "Colaborador")
                        .WithMany("NovedadRecordatorioCabs")
                        .HasForeignKey("ColaboradorId");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioDet", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioCab", "NovedadRecordatorioCab")
                        .WithMany("NovedadRecordatorioDets")
                        .HasForeignKey("NovedadRecordatorioCabId");

                    b.Navigation("NovedadRecordatorioCab");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.SolicitudPermiso", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.EstadoTarea", "EstadoTarea")
                        .WithMany("SolicitudPermiso")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Permisos.TipoPermiso", "TipoPermiso")
                        .WithMany("SolicitudPermiso")
                        .HasForeignKey("IdTipoPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoTarea");

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Vacaciones.SolicitudVacacion", b =>
                {
                    b.HasOne("EvaluacionCore.Domain.Entities.EstadoTarea", "EstadoTarea")
                        .WithMany("SolicitudVacaion")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaluacionCore.Domain.Entities.Permisos.TipoPermiso", "TipoPermiso")
                        .WithMany()
                        .HasForeignKey("TipoPermisoId");

                    b.Navigation("EstadoTarea");

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("EnrolApp.Domain.Entities.Common.Cargo", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.ClaseTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Localidad", b =>
                {
                    b.Navigation("LocalidadColaboradores");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.LocalidadColaborador", b =>
                {
                    b.Navigation("MarcacionColaboradores");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.SubclaseTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.TipoTurno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.Turno", b =>
                {
                    b.Navigation("TurnoColaboradores");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Asistencia.TurnoColaborador", b =>
                {
                    b.Navigation("MarcacionColaboradores");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Canton", b =>
                {
                    b.Navigation("CalendariosLocal");

                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Pais", b =>
                {
                    b.Navigation("CalendarioNacional");

                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Calendario.Provincia", b =>
                {
                    b.Navigation("Cantones");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Common.Cliente", b =>
                {
                    b.Navigation("LocalidadColaboradores");

                    b.Navigation("NovedadRecordatorioCabs");

                    b.Navigation("TurnoColaboradores");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.EstadoTarea", b =>
                {
                    b.Navigation("SolicitudJustificacion");

                    b.Navigation("SolicitudPermiso");

                    b.Navigation("SolicitudVacaion");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Justificacion.TipoJustificacion", b =>
                {
                    b.Navigation("SolicitudJustificacion");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Area", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Departamento", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.Empresa", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Organizacion.GrupoEmpresarial", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.NovedadRecordatorioCab", b =>
                {
                    b.Navigation("NovedadRecordatorioDets");
                });

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Permisos.TipoPermiso", b =>
                {
                    b.Navigation("SolicitudPermiso");
                });
#pragma warning restore 612, 618
        }
    }
}
