// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EvaluacionCore.Persistence.Contexts;

#nullable disable

namespace Workflow.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EvaluacionCore.Domain.Entities.Adjuntos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Estado")
                        .HasColumnType("varchar")
                        .HasColumnName("estado")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaModificacion")
                        .HasColumnOrder(10);

                    b.Property<string>("IdFeature")
                        .HasColumnType("varchar")
                        .HasColumnName("idFeature")
                        .HasColumnOrder(1);

                    b.Property<string>("IdSolicitud")
                        .HasColumnType("varchar")
                        .HasColumnName("idSolicitud")
                        .HasColumnOrder(2);

                    b.Property<string>("IdTipoSolicitud")
                        .HasColumnType("varchar")
                        .HasColumnName("idTipoSolicitud")
                        .HasColumnOrder(3);

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar")
                        .HasColumnName("identificacion")
                        .HasColumnOrder(1);

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("varchar")
                        .HasColumnName("nombreArchivo")
                        .HasColumnOrder(4);

                    b.Property<string>("RutaAcceso")
                        .HasColumnType("varchar")
                        .HasColumnName("rutaAcceso")
                        .HasColumnOrder(5);

                    b.Property<string>("UsuarioCreacion")
                        .HasColumnType("varchar")
                        .HasColumnName("usuarioCreacion")
                        .HasColumnOrder(7);

                    b.Property<string>("UsuarioModificacion")
                        .HasColumnType("varchar")
                        .HasColumnName("usuarioModificacion")
                        .HasColumnOrder(9);

                    b.HasKey("Id");

                    b.ToTable("AD_Adjuntos", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
